server.port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:jet
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update